name: DB Migrations

on:
  workflow_dispatch:
  push:
    branches: [main]
    paths:
      - 'packages/db/**'
      - '.github/workflows/db-migrate.yml'

jobs:
  migrate:
    runs-on: ubuntu-latest
    env:
      DATABASE_URL: postgresql://postgres:postgres@postgres:5432/xpenzi_ci
      PGPASSWORD: postgres
    services:
      postgres:
        image: postgres:15-alpine
        env:
          POSTGRES_DB: xpenzi_ci
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
        options: >-
          --health-cmd="pg_isready -U postgres"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Enable pnpm
        run: |
          corepack enable
          corepack prepare pnpm@8.15.4 --activate
          corepack pnpm --version

      - name: Install PostgreSQL client tools
        run: sudo apt-get update && sudo apt-get install -y postgresql-client

      - name: Wait for database
        run: |
          for i in {1..30}; do
            pg_isready -h postgres -p 5432 -U postgres && exit 0
            echo "Waiting for postgres (${i}/30)..."
            sleep 2
          done
          echo "Postgres did not become ready in time" >&2
          exit 1

      - name: Install dependencies
        run: |
          if [ -f pnpm-lock.yaml ]; then
            corepack pnpm install --frozen-lockfile
          else
            corepack pnpm install --no-frozen-lockfile
          fi

      - name: Run Prisma migrate (placeholder)
        run: corepack pnpm --filter db migrate:deploy
