name: Lambdas CI

on:
  push:
    branches: [main]
    paths:
      - 'services/**'
      - 'package.json'
      - 'pnpm-lock.yaml'
      - 'pnpm-workspace.yaml'
      - 'turbo.json'
      - '.github/workflows/lambdas.yml'
  pull_request:
    paths:
      - 'services/**'
      - 'package.json'
      - 'pnpm-lock.yaml'
      - 'pnpm-workspace.yaml'
      - 'turbo.json'
      - '.github/workflows/lambdas.yml'

jobs:
  build:
    name: Build & Test Lambdas
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'
          cache-dependency-path: pnpm-lock.yaml

      - name: Enable pnpm
        run: |
          corepack enable
          corepack prepare pnpm@8.15.4 --activate
          corepack pnpm --version

      - name: Install dependencies
        run: corepack pnpm install --frozen-lockfile

      - name: Lint
        run: corepack pnpm --filter lambdas lint

      - name: Typecheck
        run: corepack pnpm --filter lambdas typecheck

      - name: Test
        run: corepack pnpm --filter lambdas test -- --run

      - name: Bundle
        run: corepack pnpm --filter lambdas build
